query pageQuery {
  ...LayoutQueryFragment
  messageConnection {
    edges {
      node {
        id
        date
        title
        excerpt
        coordinator {
          ... on Coordinator {
            ...CoordinatorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogMessageQuery($relativePath: String!) {
  ...LayoutQueryFragment
  message(relativePath: $relativePath) {
    ...MessageParts
    coordinator {
      ... on Coordinator {
        name
        avatar
      }
    }
  }
}
